### PR TITLE
Called to Arms - Martell spoilers + <abbr>

### PR DESCRIPTION
**Pull request by mplain**
I thought about using the <abbr> tag, but i realized that while cute, it actually messes with Search, e.g. searching for "gains stealth" will fail to find "gains <abbr>stealth</abbr>".

Should I remove it from the first two packsand from Core?

### CODE REVIEW

**Comment by Alsciende** [comment]
Ok, let's remove all the `<abbr>` tags. I'll find a way to put them back when I display a card text.

**Comment by Alsciende** [comment]
I'll do it.

**Comment by Alsciende** [comment]
Done in https://github.com/Alsciende/thronesdb-json-data/commit/1ab7a90355bb88c3a242c967a61b90936aa88ed5

**Comment by mplain** [comment]
You even removed it from my comment, now it looks silly :)

**Pull request merged**
