### PR TITLE
Valyrian Draft Set

### PR DESCRIPTION
**Pull request by mplain**

### CODE REVIEW

**Comment by Alsciende** [comment]
I assume these cards will be released in future Chapter Packs, am I right?

**Comment by mplain** [comment]
No, this is a Draft Set and the cards from it say "Draft format only".

I think that a database should include these for reference (netrunnerdb includes draft only cards), also some people might want to post their draft decks (from major events and such).

**Comment by Alsciende** [comment]
Merged into branch "draft"

**Comment by Alsciende** [comment]
Ok, I merged "draft" into "master". This data will be live soon.

**Pull request closed without merging**
