### PR TITLE
Lions of Casterly Rock

### PR DESCRIPTION
**Pull request by mplain**
gt15_card_cersei
gt15_card_tyrion
gt15_card_moon-brothers
gt15_card_golden-tooth
gt15_card_last-hearth-scouts
gt15_card_ser-barristan-selmy

### CODE REVIEW

**Comment by Alsciende** [comment]
I don't know how this passed. There's a erroneous comma at the end of the file.

**Comment by Alsciende** [comment]
Also, `octgn_id` must be `null`, not empty (`""`).

**Comment by Alsciende** [comment]
The validator was a mess anyway. All fixed. Thanks for the Pull Request :)

**Comment by mplain** [comment]
Got it, will do. Thanks for the quick upload :)

[+ subtle reminder about uploading the rulebook in html]

**Pull request merged**
