### PR TITLE
Lions of Casterly Rock - full spoilers

### PR DESCRIPTION
**Pull request by mplain**

### CODE REVIEW

**Comment by mplain** [comment]
Cedric would you approve this please (or is there a reason why you don't?)

All card text is legit, as evidenced by attached images, and the reason for unreleased cards to be in the database is that for some users (me included) the Search function is no less important than the deckbuilder.

I'd also very much appreciate if you uploaded the official FAQ on the website.

In general it would be nice to get some feedback from you as well, if you want me to do or not do something in a certain way, just tell me. The wall of silence is upsetting. I'm not pestering you on facebook anymore, but it would be nice to get a responce every once in a while. You're the boss, it's your website, you're busy, and I'm just helping fill it with data, but it would be nice to have my efforts acknowledged...

**Comment by Alsciende** [comment]
Sorry for the silence, I'm quite busy atm with a new job and all. I uploaded that data. In general I'd prefer to wait until the pack is released before uploading. It helps to make sure the data is correct, and it prevents issue with OCTGN.

**Comment by mplain** [comment]
Thank you. I will only post data that is legit - no chinese spoilers or muddy pictures. But I'd appreciate it if you kept uploading new legit preview data to the website - people use the database, post links to upcoming cards in discussions, and I use the Search to ask and answer rules questions. Thanks.

**Comment by Alsciende** [comment]
I'll do my best to be more reactive from now on :)

**Comment by mplain** [comment]
Thank you! :)

**Comment by mplain** [comment]
Look, it's not just me! ;)
https://www.facebook.com/groups/agot2ndedition/permalink/1297464396933062

**Pull request merged**
