### PR TITLE
TtB - fixed formatting

### PR DESCRIPTION
**Pull request by mplain**

### CODE REVIEW

**Comment by Alsciende** [comment]
Why do you want to remove the <abbr> tags?

I would merge a PR without the <abbr> commit.

**Comment by mplain** [comment]
We discussed removing the <abbr> tags earlier here: https://github.com/Alsciende/thronesdb-json-data/pull/44

You have run a script to remove tags in this commit: https://github.com/Alsciende/thronesdb-json-data/commit/1ab7a90355bb88c3a242c967a61b90936aa88ed5

I assumed that something went wrong and you fell back to a previous version of the database, maybe due to some glitch. Maybe I didn't understand your intention?

**Comment by Alsciende** [comment]
Yes, it looks like we misunderstood each other.

I agreed to remove the <abbr>tags inside sentences because, as you pointed out, it messes with the search.

But the <abbr> tags on single keywords don't mess with the search, AFAIK. They are still a bit helpful for new players, just in case.

That being said... I'm going to add the <abbr> tag programmatically. So the json data doesn't have to include it. It'll be easier for everybody.

**Comment by mplain** [comment]
Oh, I see. Well, glad that it's all sorted out now :)

**Pull request merged**
